- hosts: all
  tasks:
  - name: a simple block
    block:
    - debug:
        msg: 'I execute normally'
    - name: i force a failure
      command: "false"
    - debug:
        msg: 'I never execute, due to the above task failing, :-('
    rescue:
      - debug:
          msg: 'I caught an error'
      - name: i force a failure in middle of recovery! >:-)
        command: "false"
      - debug:
          msg: 'I also never execute :-('
    always:
      - debug:
          msg: "This always executes"