---
- hosts: all
  user : ec2-user
  become: true
  pre_tasks:
  - name: Ping
    ping:
  tasks:
  - dnf:
      name=nginx
      state=present
  post_tasks:
  - name: make sure nginx is running
    service: 
      name=nginx 
      state=started
