---
- name: Play1
  hosts: all
  become: true
  tasks:
   - name: Install Nginx
     yum: pkg=nginx update_cache=true
     notify:
      - start-nginx

  handlers:
   - name: start-nginx
     service: 
      name: nginx 
      state: started
- name: Play2
  hosts: all
  become: true
  tasks:
  - name: template configuration file 
    copy:
      src: file.txt
      dest: /tmp/file2.txt 
    notify:
    - restart-memcached 
    - restart-apache

  handlers:
  - name: restart-memcached 
    debug: 
      msg: "Restarting Memcached"
  - name: restart-apache 
    debug: 
      msg: "Restarting Apache"
  