--- # My First YAML playbook for ansible
- hosts: dev
  connection: ssh
  become: true # become root user
  gather_facts: no
  pre_tasks:
  - name: pre-task
    debug: 
      msg: "This is a pre-task, it will run before main task"
  tasks:
  - name: Install Git
    command: yum install git -y
  - name: Install Nginx with Module
    dnf: 
      name=nginx
      state=present
  post_tasks:
  - name: post-task
    debug: 
      msg: "This is a post-task, it will run after main task"