--- # when playbook example
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  vars:
    instructor: "Ali Kahoot"

  tasks:
    - name: Hello Instructor
      debug: 
        msg: "The instructor is {{ instructor }}"

    - name: Hello Class
      debug: 
        msg: "Hello {{ batch }} batch"

    